export {default as Header} from './Header/Header'
export {default as Footer} from '../section/Footer/Footer'
export {default as Hero} from '../section/Hero/Hero'
export {default as GammingLibrary} from '../section/GammingLibrary/GammingLibrary'
export {default as MostPopular} from '../section/MostPopular/MostPopular'